language: python
python:
  - "2.7"
  - "3.5"

addons:
  apt:
    packages:
    - python-sklearn

before_install:
  - pip install cython
  - pip install numpy
  - python setup.py build_ext --inplace

# command to run tests
script: nosetests