language: python
python:
  - "2.7"
  - "3.5"

addons:
  apt:
    packages:
      # only required by the DISTRIB="ubuntu" build:
      - python-scipy

before_install:
  - pip install cython
  - pip install numpy
  - pip install scikit-learn
  - python setup.py build_ext --inplace

# command to run tests
script: nosetests