sudo: required
dist: trusty


language: python
python:
  - "2.7"
  - "3.5"


addons:
  apt:
    packages:
      - libatlas3gf-base
      - libatlas-dev
      - python-scipy


before_install:
  - pip install cython
  - pip install scikit-learn
  - python setup.py build_ext --inplace


# command to run tests
script: nosetests