language: python
python:
  - "2.7"
  - "3.5"

sudo: required

before_install:
  - sudo apt-get install python-sklearn
  - pip install cython
  - pip install numpy
  - python setup.py build_ext --inplace

# command to run tests
script: nosetests