language: python
python:
  - "2.7"
  - "3.5"

before_install:
  - pip install cython
  - pip install numpy
  - pip install scipy
  - pip install scikit-learn
  - python setup.py build_ext --inplace

# command to run tests
script: nosetests