#!/bin/bash
fRes="../res/TDesired"
fDatos="../data"

clear
echo "Instalando EvoDAG...."
cd /home/claudia/Documentos/DOCTORADO/CODIGO/EvoDAG
#cd /shared/cnsanchez/EvoDAG
python setup.py build_ext --inplace
python setup.py install
nosetests EvoDAG

test="_test_data_"
train="_train_"

archivo="banana"
clear
echo "banana.........................................................."
for ((var=1;var<=100;var++))
do  
    echo EvoDAG-params -C -P $fRes/$archivo$test$var.params -u 32 $fDatos/$archivo$train$var.csv
    EvoDAG-params -C -P $fRes/$archivo$test$var.params -u 32 $fDatos/$archivo$train$var.csv
    echo EvoDAG-train -P $fRes/$archivo$test$var.params -m $fRes/$archivo$test$var.model -u 32 $fDatos/$archivo$train$var.csv
    EvoDAG-train -P $fRes/$archivo$test$var.params -m $fRes/$archivo$test$var.model -u 32 $fDatos/$archivo$train$var.csv
    echo EvoDAG-predict -m $fRes/$archivo$test$var.model -o $fRes/$archivo$test$var.predict -u 32 $fDatos/$archivo$test$var.csv
    EvoDAG-predict -m $fRes/$archivo$test$var.model -o $fRes/$archivo$test$var.predict -u 32 $fDatos/$archivo$test$var.csv
done

archivo="breast-cancer"
clear
echo "breast-cancer..............................................."
for ((var=1;var<=100;var++))
do  
    echo EvoDAG-params -C -P $fRes/$archivo$test$var.params -u 32 $fDatos/$archivo$train$var.csv
    EvoDAG-params -C -P $fRes/$archivo$test$var.params -u 32 $fDatos/$archivo$train$var.csv
    echo EvoDAG-train -P $fRes/$archivo$test$var.params -m $fRes/$archivo$test$var.model -u 32 $fDatos/$archivo$train$var.csv
    EvoDAG-train -P $fRes/$archivo$test$var.params -m $fRes/$archivo$test$var.model -u 32 $fDatos/$archivo$train$var.csv
    echo EvoDAG-predict -m $fRes/$archivo$test$var.model -o $fRes/$archivo$test$var.predict -u 32 $fDatos/$archivo$test$var.csv
    EvoDAG-predict -m $fRes/$archivo$test$var.model -o $fRes/$archivo$test$var.predict -u 32 $fDatos/$archivo$test$var.csv
done

archivo="diabetis"
clear
echo "diabetis..............................................."
for ((var=1;var<=100;var++))
do  
    echo EvoDAG-params -C -P $fRes/$archivo$test$var.params -u 32 $fDatos/$archivo$train$var.csv
    EvoDAG-params -C -P $fRes/$archivo$test$var.params -u 32 $fDatos/$archivo$train$var.csv
    echo EvoDAG-train -P $fRes/$archivo$test$var.params -m $fRes/$archivo$test$var.model -u 32 $fDatos/$archivo$train$var.csv
    EvoDAG-train -P $fRes/$archivo$test$var.params -m $fRes/$archivo$test$var.model -u 32 $fDatos/$archivo$train$var.csv
    echo EvoDAG-predict -m $fRes/$archivo$test$var.model -o $fRes/$archivo$test$var.predict -u 32 $fDatos/$archivo$test$var.csv
    EvoDAG-predict -m $fRes/$archivo$test$var.model -o $fRes/$archivo$test$var.predict -u 32 $fDatos/$archivo$test$var.csv
done

archivo="flare-solar"
clear
echo "flare-solar..............................................."
for ((var=1;var<=100;var++))
do  
    echo EvoDAG-params -C -P $fRes/$archivo$test$var.params -u 32 $fDatos/$archivo$train$var.csv
    EvoDAG-params -C -P $fRes/$archivo$test$var.params -u 32 $fDatos/$archivo$train$var.csv
    echo EvoDAG-train -P $fRes/$archivo$test$var.params -m $fRes/$archivo$test$var.model -u 32 $fDatos/$archivo$train$var.csv
    EvoDAG-train -P $fRes/$archivo$test$var.params -m $fRes/$archivo$test$var.model -u 32 $fDatos/$archivo$train$var.csv
    echo EvoDAG-predict -m $fRes/$archivo$test$var.model -o $fRes/$archivo$test$var.predict -u 32 $fDatos/$archivo$test$var.csv
    EvoDAG-predict -m $fRes/$archivo$test$var.model -o $fRes/$archivo$test$var.predict -u 32 $fDatos/$archivo$test$var.csv
done

archivo="german"
clear
echo "german..............................................."
for ((var=1;var<=100;var++))
do  
    echo EvoDAG-params -C -P $fRes/$archivo$test$var.params -u 32 $fDatos/$archivo$train$var.csv
    EvoDAG-params -C -P $fRes/$archivo$test$var.params -u 32 $fDatos/$archivo$train$var.csv
    echo EvoDAG-train -P $fRes/$archivo$test$var.params -m $fRes/$archivo$test$var.model -u 32 $fDatos/$archivo$train$var.csv
    EvoDAG-train -P $fRes/$archivo$test$var.params -m $fRes/$archivo$test$var.model -u 32 $fDatos/$archivo$train$var.csv
    echo EvoDAG-predict -m $fRes/$archivo$test$var.model -o $fRes/$archivo$test$var.predict -u 32 $fDatos/$archivo$test$var.csv
    EvoDAG-predict -m $fRes/$archivo$test$var.model -o $fRes/$archivo$test$var.predict -u 32 $fDatos/$archivo$test$var.csv
done

archivo="heart"
clear
echo "heart..............................................."
for ((var=1;var<=100;var++))
do  
    echo EvoDAG-params -C -P $fRes/$archivo$test$var.params -u 32 $fDatos/$archivo$train$var.csv
    EvoDAG-params -C -P $fRes/$archivo$test$var.params -u 32 $fDatos/$archivo$train$var.csv
    echo EvoDAG-train -P $fRes/$archivo$test$var.params -m $fRes/$archivo$test$var.model -u 32 $fDatos/$archivo$train$var.csv
    EvoDAG-train -P $fRes/$archivo$test$var.params -m $fRes/$archivo$test$var.model -u 32 $fDatos/$archivo$train$var.csv
    echo EvoDAG-predict -m $fRes/$archivo$test$var.model -o $fRes/$archivo$test$var.predict -u 32 $fDatos/$archivo$test$var.csv
    EvoDAG-predict -m $fRes/$archivo$test$var.model -o $fRes/$archivo$test$var.predict -u 32 $fDatos/$archivo$test$var.csv
done

archivo="image"
clear
echo "image..............................................."
for ((var=1;var<=20;var++))
do  
    echo EvoDAG-params -C -P $fRes/$archivo$test$var.params -u 32 $fDatos/$archivo$train$var.csv
    EvoDAG-params -C -P $fRes/$archivo$test$var.params -u 32 $fDatos/$archivo$train$var.csv
    echo EvoDAG-train -P $fRes/$archivo$test$var.params -m $fRes/$archivo$test$var.model -u 32 $fDatos/$archivo$train$var.csv
    EvoDAG-train -P $fRes/$archivo$test$var.params -m $fRes/$archivo$test$var.model -u 32 $fDatos/$archivo$train$var.csv
    echo EvoDAG-predict -m $fRes/$archivo$test$var.model -o $fRes/$archivo$test$var.predict -u 32 $fDatos/$archivo$test$var.csv
    EvoDAG-predict -m $fRes/$archivo$test$var.model -o $fRes/$archivo$test$var.predict -u 32 $fDatos/$archivo$test$var.csv
done

archivo="ringnorm"
clear
echo "ringnorm..............................................."
for ((var=1;var<=100;var++))
do  
    echo EvoDAG-params -C -P $fRes/$archivo$test$var.params -u 32 $fDatos/$archivo$train$var.csv
    EvoDAG-params -C -P $fRes/$archivo$test$var.params -u 32 $fDatos/$archivo$train$var.csv
    echo EvoDAG-train -P $fRes/$archivo$test$var.params -m $fRes/$archivo$test$var.model -u 32 $fDatos/$archivo$train$var.csv
    EvoDAG-train -P $fRes/$archivo$test$var.params -m $fRes/$archivo$test$var.model -u 32 $fDatos/$archivo$train$var.csv
    echo EvoDAG-predict -m $fRes/$archivo$test$var.model -o $fRes/$archivo$test$var.predict -u 32 $fDatos/$archivo$test$var.csv
    EvoDAG-predict -m $fRes/$archivo$test$var.model -o $fRes/$archivo$test$var.predict -u 32 $fDatos/$archivo$test$var.csv
done

archivo="splice"
clear
echo "splice.............................................."
for ((var=1;var<=20;var++))
do  
    echo EvoDAG-params -C -P $fRes/$archivo$test$var.params -u 32 $fDatos/$archivo$train$var.csv
    EvoDAG-params -C -P $fRes/$archivo$test$var.params -u 32 $fDatos/$archivo$train$var.csv
    echo EvoDAG-train -P $fRes/$archivo$test$var.params -m $fRes/$archivo$test$var.model -u 32 $fDatos/$archivo$train$var.csv
    EvoDAG-train -P $fRes/$archivo$test$var.params -m $fRes/$archivo$test$var.model -u 32 $fDatos/$archivo$train$var.csv
    echo EvoDAG-predict -m $fRes/$archivo$test$var.model -o $fRes/$archivo$test$var.predict -u 32 $fDatos/$archivo$test$var.csv
    EvoDAG-predict -m $fRes/$archivo$test$var.model -o $fRes/$archivo$test$var.predict -u 32 $fDatos/$archivo$test$var.csv
done

archivo="thyroid"
clear
echo "thryroid.............................................."
for ((var=1;var<=100;var++))
do  
    echo EvoDAG-params -C -P $fRes/$archivo$test$var.params -u 32 $fDatos/$archivo$train$var.csv
    EvoDAG-params -C -P $fRes/$archivo$test$var.params -u 32 $fDatos/$archivo$train$var.csv
    echo EvoDAG-train -P $fRes/$archivo$test$var.params -m $fRes/$archivo$test$var.model -u 32 $fDatos/$archivo$train$var.csv
    EvoDAG-train -P $fRes/$archivo$test$var.params -m $fRes/$archivo$test$var.model -u 32 $fDatos/$archivo$train$var.csv
    echo EvoDAG-predict -m $fRes/$archivo$test$var.model -o $fRes/$archivo$test$var.predict -u 32 $fDatos/$archivo$test$var.csv
    EvoDAG-predict -m $fRes/$archivo$test$var.model -o $fRes/$archivo$test$var.predict -u 32 $fDatos/$archivo$test$var.csv
done

archivo="titanic"
clear
echo "titanic.............................................."
for ((var=1;var<=100;var++))
do  
    echo EvoDAG-params -C -P $fRes/$archivo$test$var.params -u 32 $fDatos/$archivo$train$var.csv
    EvoDAG-params -C -P $fRes/$archivo$test$var.params -u 32 $fDatos/$archivo$train$var.csv
    echo EvoDAG-train -P $fRes/$archivo$test$var.params -m $fRes/$archivo$test$var.model -u 32 $fDatos/$archivo$train$var.csv
    EvoDAG-train -P $fRes/$archivo$test$var.params -m $fRes/$archivo$test$var.model -u 32 $fDatos/$archivo$train$var.csv
    echo EvoDAG-predict -m $fRes/$archivo$test$var.model -o $fRes/$archivo$test$var.predict -u 32 $fDatos/$archivo$test$var.csv
    EvoDAG-predict -m $fRes/$archivo$test$var.model -o $fRes/$archivo$test$var.predict -u 32 $fDatos/$archivo$test$var.csv
done

archivo="twonorm"
clear
echo "twonorm.............................................."
for ((var=1;var<=100;var++))
do  
    echo EvoDAG-params -C -P $fRes/$archivo$test$var.params -u 32 $fDatos/$archivo$train$var.csv
    EvoDAG-params -C -P $fRes/$archivo$test$var.params -u 32 $fDatos/$archivo$train$var.csv
    echo EvoDAG-train -P $fRes/$archivo$test$var.params -m $fRes/$archivo$test$var.model -u 32 $fDatos/$archivo$train$var.csv
    EvoDAG-train -P $fRes/$archivo$test$var.params -m $fRes/$archivo$test$var.model -u 32 $fDatos/$archivo$train$var.csv
    echo EvoDAG-predict -m $fRes/$archivo$test$var.model -o $fRes/$archivo$test$var.predict -u 32 $fDatos/$archivo$test$var.csv
    EvoDAG-predict -m $fRes/$archivo$test$var.model -o $fRes/$archivo$test$var.predict -u 32 $fDatos/$archivo$test$var.csv
done

archivo="waveform"
clear
echo "waveform.............................................."
for ((var=1;var<=100;var++))
do  
    echo EvoDAG-params -C -P $fRes/$archivo$test$var.params -u 32 $fDatos/$archivo$train$var.csv
    EvoDAG-params -C -P $fRes/$archivo$test$var.params -u 32 $fDatos/$archivo$train$var.csv
    echo EvoDAG-train -P $fRes/$archivo$test$var.params -m $fRes/$archivo$test$var.model -u 32 $fDatos/$archivo$train$var.csv
    EvoDAG-train -P $fRes/$archivo$test$var.params -m $fRes/$archivo$test$var.model -u 32 $fDatos/$archivo$train$var.csv
    echo EvoDAG-predict -m $fRes/$archivo$test$var.model -o $fRes/$archivo$test$var.predict -u 32 $fDatos/$archivo$test$var.csv
    EvoDAG-predict -m $fRes/$archivo$test$var.model -o $fRes/$archivo$test$var.predict -u 32 $fDatos/$archivo$test$var.csv
done
