about:
  home: https://github.com/mgraffg/EvoDAG
  license: Apache License
  summary: Evolving Directed Acyclic Graph (EvoDAG) is a steady-state Genetic Programming system with tournament selection.

package:
  name: evodag
  version: "0.4.6.1"
  depends: ["numpy>=1.6.2", "cython>=0.19.2", "sparsearray>=0.8.9"]

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy
    - cython
    - sparsearray

  run:
    - python
    - numpy
    - sparsearray

test:
  # Python imports
  imports:
    - EvoDAG

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - EvoDAG-params --help
    - EvoDAG-train --help
    - EvoDAG-predict --help

  requires:
    # Put any additional test requirements here.  For example
    - numpy
    - cython
    - sparsearray
