package:
  name: evodag
  version: "0.4.1"

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python

test:
  # Python imports
  imports:
    - EvoDAG

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - EvoDAG-params --help
    - EvoDAG-train --help
    - EvoDAG-predict --help

  requires:
    # Put any additional test requirements here.  For example
    - numpy

about:
  home: https://github.com/mgraffg/EvoDAG
  summary: Evolving Directed Acyclic Graph (EvoDAG) is a steady-state Genetic Programming system with tournament selection.
  license: Apache
